### PR TITLE
Don't match braces of namespace alias

### LINKED ISSUE #2387: Crash on namespace alias inside function
Current uncrustify version crashes on following code:
```
namespace b{}
void f()
{
namespace a = b;
}
```
This code processed fine:
```
namespace b{}
namespace a = b;
void f()
{
}
```

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Tweak the code that tries to match namespace braces to recognize and ignore namespace aliases, which don't have associated braces. Also, check if a brace was found before trying to dereference the matching token.

This fixes a crash if there is no brace anywhere in the input after a namespace or namespace alias. The latter is perfectly valid code, and while the former is malformed, it is better to complain than to crash.

Fixes #2387.

### CODE REVIEW

File: src/newlines.cpp [hunk 1]
```diff
@@ -3737,11 +3737,20 @@ void newlines_cleanup_braces(bool first)
          }
       }
       else if (  chunk_is_token(pc, CT_NAMESPACE)
-              && pc->parent_type != CT_USING)
+              && pc->parent_type != CT_USING
+              && pc->next
```
Comment (gmaurel) [inline src/newlines.cpp]: I prefer pc->next != nullptr

Comment (mwoehlke-kitware) [reply src/newlines.cpp]: Done. I also tweaked the code to be a bit more robust, e.g. in the face of pathological code with comments / newlines in the middle of a namespace alias. (I can't imagine such code being common, but...)

Comment (gmaurel) [reply src/newlines.cpp]: Fine
