### PR TITLE
Fix OC switch case indent when in OC block

### LINKED ISSUE #3813: Extra indent added in switch case in ObjC block
input
```
- (void)func {
  func2(^{
    switch (type) {
      case one:
        break;
      default:
        break;
    }
  });
}
```

bad output (expected to be same as input)
```
- (void)func
{
  func2(^{
    switch (type) {
        case one:
          break;
        default:
          break;
    }
  });
}

```

config
```
indent_switch_case = 2
indent_with_tabs = 0
indent_columns = 2
```

command
```
./uncrustify -l OC+ -c tmp.cfg -f test_file_original.m -o test_file_original_unc.m -p myExample.p -L A 2>myExample.A -ds dump
```

### PR DESCRIPTION
**Pull request by PoeticPete**
Fixes #3813

input
```
- (void)func {
  func2(^{
    switch (type) {
      case one:
        break;
      default:
        break;
    }
  });
}
```

bad output (expected to be same as input)
```
- (void)func
{
  func2(^{
    switch (type) {
        case one:
          break;
        default:
          break;
    }
  });
}

```

config
```
indent_switch_case = 2
indent_with_tabs = 0
indent_columns = 2
```

command
```
./uncrustify -l OC+ -c tmp.cfg -f test_file_original.m -o test_file_original_unc.m -p myExample.p -L A 2>myExample.A -ds dump
```

### CODE REVIEW

File: src/indent.cpp [hunk 1]
```diff
@@ -2040,6 +2040,11 @@ void indent_text()
                log_indent();
                indent_column_set(frm.prev().pc->column);
             }
+            // Issue #3183
```
Comment (micheleCTDEAdmin) [inline src/indent.cpp:2043]: This is issue #3813, not #3183

**Review by micheleCTDEAdmin — CHANGES_REQUESTED** [review]
Comment needs to be amended.

Other than that, it seems a very custom-made solution. How about blocks that are not `switch`? Would probably be better to have a general solution I think. Maybe in that case we don't even need a new bit in the PCF list...

**Comment by PoeticPete** [comment]
#3761 fixed the same issue in cpp and the solution was to check for `PCF_IN_LAMBDA` before running indent logic.

Re: adding additional flag -- If we have a `PCF_IN_LAMBDA` flag, it makes sense to have a flag for OC blocks too?

Re: making this more generalizable -- the issue is that switch cases are falling into the generalized `else` block [here](https://github.com/uncrustify/uncrustify/blame/6ebc9634a21a8f3e7fba713810bdc51514eb86e0/src/indent.cpp#L2006). Basically we are incorrectly assuming the switch block is `({ ... })`. It seems like the other conditions are looking for cases like `({` to determine indent logic, which isn't the case for switch statements.

**Review by micheleCTDEAdmin — APPROVED** [review]
Ok, makes sense. Thanks for the feedback and amending.
