### PR TITLE
Avoid null pointer dereference when formatting function-like macros

### LINKED ISSUE #3274: Crash when parsing macro if nl_func_decl_args_multi_line and nl_func_leave_one_liners are true
Config file:

```
nl_func_decl_args_multi_line = true
nl_func_leave_one_liners = true
```

Test code:

```
#define FOO
#define BAR()

FOO
BAR()
```

Log (from `uncrustify -LA`):

```
Uncrustify_d-0.73.0_f
config_file = test.cfg
output_file = null
source_file = null
source_list = null
tracking    = null
prefix      = null
suffix      = null
assume      = null
replace     = false
no_backup   = false
detect      = false
check       = false
if_changed  = false
log_rule(main:725): rule is 'nl_max'
log_rule(load_header_files:1263): rule is 'cmt_insert_file_header'
log_rule(load_header_files:1271): rule is 'cmt_insert_file_footer'
log_rule(load_header_files:1278): rule is 'cmt_insert_func_header'
log_rule(load_header_files:1285): rule is 'cmt_insert_class_header'
log_rule(load_header_files:1292): rule is 'cmt_insert_oc_msg_header'
log_rule(load_header_files:1299): rule is 'cmt_reflow_fold_regex_file'
Output suffix: .uncrustify
load_mem_file: 'simpleFont5.c' encoding looks like ASCII (0)
Parsing: simpleFont5.c as language C
log_rule(uncrustify_file:1973): rule is 'utf8_force'
log_rule(uncrustify_file:1974): rule is 'utf8_byte'
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
log_rule(find_punctuator:66): rule is 'enable_digraphs'
parse_next(2475): orig_line is 1, orig_col is 1, pc->text() '#'
   pc->type is NONE, pc->parent_type is NONE => *type is POUND, *parent_type is NONE
tokenize(2816): orig_line is 1, orig_col is 1, pc->text() '#'
   pc->type is POUND, pc->parent_type is NONE => *type is PREPROC, *parent_type is NONE
chunk_flags_set_real(832): 0000000200000000^0000000000000001=0000000200000001
   orig_line is 1, orig_col is 1, text() '#', type is PREPROC, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 1, orig_col is 1, text() '#', type is PREPROC, orig_col_end is 2
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_word(1583): orig_line is 1, orig_col is 2, pc->text() 'define'
   pc->type is NONE, pc->parent_type is NONE => *type is WORD, *parent_type is NONE
parse_word(1627): orig_line is 1, orig_col is 2, pc->text() 'define'
   pc->type is WORD, pc->parent_type is NONE => *type is PP_DEFINE, *parent_type is NONE
chunk_flags_set_real(832): 0000000000000000^0000000000000001=0000000000000001
   orig_line is 1, orig_col is 2, text() 'define', type is PP_DEFINE, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 1, orig_col is 2, text() 'define', type is PP_DEFINE, orig_col_end is 8
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_whitespace(1847): orig_line is 1, orig_col is 8, pc->text() ''
   pc->type is NONE, pc->parent_type is NONE => *type is WHITESPACE, *parent_type is NONE
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_word(1583): orig_line is 1, orig_col is 9, pc->text() 'FOO'
   pc->type is NONE, pc->parent_type is NONE => *type is WORD, *parent_type is NONE
parse_word(1600): orig_line is 1, orig_col is 9, pc->text() 'FOO'
   pc->type is WORD, pc->parent_type is NONE => *type is MACRO, *parent_type is NONE
log_rule(parse_word:1602): rule is 'pp_ignore_define_body'
chunk_flags_set_real(832): 0000000000000000^0000000000000001=0000000000000001
   orig_line is 1, orig_col is 9, text() 'FOO', type is MACRO, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 1, orig_col is 9, text() 'FOO', type is MACRO, orig_col_end is 12
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_whitespace(1847): orig_line is 1, orig_col is 12, pc->text() <Newline>
   pc->type is NONE, pc->parent_type is NONE => *type is NEWLINE, *parent_type is NONE
tokenize(2825): orig_line is 1, orig_col is 12, <Newline>, nl is 1
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
log_rule(find_punctuator:66): rule is 'enable_digraphs'
parse_next(2475): orig_line is 2, orig_col is 1, pc->text() '#'
   pc->type is NONE, pc->parent_type is NONE => *type is POUND, *parent_type is NONE
tokenize(2816): orig_line is 2, orig_col is 1, pc->text() '#'
   pc->type is POUND, pc->parent_type is NONE => *type is PREPROC, *parent_type is NONE
chunk_flags_set_real(832): 0000000200000000^0000000000000001=0000000200000001
   orig_line is 2, orig_col is 1, text() '#', type is PREPROC, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 2, orig_col is 1, text() '#', type is PREPROC, orig_col_end is 2
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_word(1583): orig_line is 2, orig_col is 2, pc->text() 'define'
   pc->type is NONE, pc->parent_type is NONE => *type is WORD, *parent_type is NONE
parse_word(1627): orig_line is 2, orig_col is 2, pc->text() 'define'
   pc->type is WORD, pc->parent_type is NONE => *type is PP_DEFINE, *parent_type is NONE
chunk_flags_set_real(832): 0000000000000000^0000000000000001=0000000000000001
   orig_line is 2, orig_col is 2, text() 'define', type is PP_DEFINE, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 2, orig_col is 2, text() 'define', type is PP_DEFINE, orig_col_end is 8
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_whitespace(1847): orig_line is 2, orig_col is 8, pc->text() ''
   pc->type is NONE, pc->parent_type is NONE => *type is WHITESPACE, *parent_type is NONE
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_word(1583): orig_line is 2, orig_col is 9, pc->text() 'BAR'
   pc->type is NONE, pc->parent_type is NONE => *type is WORD, *parent_type is NONE
parse_word(1596): orig_line is 2, orig_col is 9, pc->text() 'BAR'
   pc->type is WORD, pc->parent_type is NONE => *type is MACRO_FUNC, *parent_type is NONE
chunk_flags_set_real(832): 0000000000000000^0000000000000001=0000000000000001
   orig_line is 2, orig_col is 9, text() 'BAR', type is MACRO_FUNC, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 2, orig_col is 9, text() 'BAR', type is MACRO_FUNC, orig_col_end is 12
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
log_rule(find_punctuator:66): rule is 'enable_digraphs'
parse_next(2475): orig_line is 2, orig_col is 12, pc->text() '('
   pc->type is NONE, pc->parent_type is NONE => *type is PAREN_OPEN, *parent_type is NONE
chunk_flags_set_real(832): 0000000200000000^0000000000000001=0000000200000001
   orig_line is 2, orig_col is 12, text() '(', type is PAREN_OPEN, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 2, orig_col is 12, text() '(', type is PAREN_OPEN, orig_col_end is 13
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
log_rule(find_punctuator:66): rule is 'enable_digraphs'
parse_next(2475): orig_line is 2, orig_col is 13, pc->text() ')'
   pc->type is NONE, pc->parent_type is NONE => *type is PAREN_CLOSE, *parent_type is NONE
chunk_flags_set_real(832): 0000000200000000^0000000000000001=0000000200000001
   orig_line is 2, orig_col is 13, text() ')', type is PAREN_CLOSE, parent_type is NONE,
   [CallStack:]
tokenize(2836): orig_line is 2, orig_col is 13, text() ')', type is PAREN_CLOSE, orig_col_end is 14
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_whitespace(1847): orig_line is 2, orig_col is 14, pc->text() <Newline>
   pc->type is NONE, pc->parent_type is NONE => *type is NEWLINE, *parent_type is NONE
tokenize(2825): orig_line is 2, orig_col is 14, <Newline>, nl is 2
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_word(1583): orig_line is 4, orig_col is 1, pc->text() 'FOO'
   pc->type is NONE, pc->parent_type is NONE => *type is WORD, *parent_type is NONE
tokenize(2836): orig_line is 4, orig_col is 1, text() 'FOO', type is WORD, orig_col_end is 4
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_whitespace(1847): orig_line is 4, orig_col is 4, pc->text() <Newline>
   pc->type is NONE, pc->parent_type is NONE => *type is NEWLINE, *parent_type is NONE
tokenize(2825): orig_line is 4, orig_col is 4, <Newline>, nl is 1
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_word(1583): orig_line is 5, orig_col is 1, pc->text() 'BAR'
   pc->type is NONE, pc->parent_type is NONE => *type is WORD, *parent_type is NONE
tokenize(2836): orig_line is 5, orig_col is 1, text() 'BAR', type is WORD, orig_col_end is 4
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
log_rule(find_punctuator:66): rule is 'enable_digraphs'
parse_next(2475): orig_line is 5, orig_col is 4, pc->text() '('
   pc->type is NONE, pc->parent_type is NONE => *type is PAREN_OPEN, *parent_type is NONE
tokenize(2836): orig_line is 5, orig_col is 4, text() '(', type is PAREN_OPEN, orig_col_end is 5
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
log_rule(find_punctuator:66): rule is 'enable_digraphs'
parse_next(2475): orig_line is 5, orig_col is 5, pc->text() ')'
   pc->type is NONE, pc->parent_type is NONE => *type is PAREN_CLOSE, *parent_type is NONE
tokenize(2836): orig_line is 5, orig_col is 5, text() ')', type is PAREN_CLOSE, orig_col_end is 6
log_rule(parse_next:2123): rule is 'disable_processing_nl_cont'
parse_whitespace(1847): orig_line is 5, orig_col is 6, pc->text() <Newline>
   pc->type is NONE, pc->parent_type is NONE => *type is NEWLINE, *parent_type is NONE
tokenize(2825): orig_line is 5, orig_col is 6, <Newline>, nl is 1
log_rule(tokenize:2840): rule is 'newlines'
Using LF line endings
tokenize_cleanup(1064): orig_line is 1, orig_col is 1, pc->text() '#'
   pc->type is PREPROC, pc->parent_type is NONE => *type is PP_DEFINE, *parent_type is NONE
tokenize_cleanup(1064): orig_line is 2, orig_col is 1, pc->text() '#'
   pc->type is PREPROC, pc->parent_type is NONE => *type is PP_DEFINE, *parent_type is NONE
tokenize_cleanup(421): orig_line is 4, orig_col is 1, pc->text() 'FOO'
   pc->type is WORD, pc->parent_type is NONE => *type is TYPE, *parent_type is NONE
brace_cleanup(192): orig_line is 1, orig_col is 1, text() is '#'
fl_push(136): frame_count is 1
ParseFrame::push(push:152): orig_line is 0, orig_col is 0, type is NONE, brace_level is 0, level is 0, pse_tos: 0 -> 1
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 1, orig_col is 1, type is PREPROC, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x200000001:IN_PREPROC,PUNCTUATOR]
parse_cleanup(350): orig_line is 1, type is PREPROC, text() is '#'
parse_cleanup(352): frm.stmt_count is 0, frm.expr_count is 0
chunk_flags_set_real(832): 0000000200000001^00000000000c0000=00000002000c0001
   orig_line is 1, orig_col is 1, text() '#', type is PREPROC, parent_type is PP_DEFINE,
   [CallStack: chunk_flags_set_real:824, parse_cleanup:340, brace_cleanup:183]
parse_cleanup(364): orig_line is 1, 1.marked '#' as stmt, start stmt_count is 0, expr_count is 0
parse_cleanup(371): frm.stmt_count is 1, frm.expr_count is 1
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 1, orig_col is 1, text() is '#'
print_stack(161): str is '#' [PP_DEFINE]
brace_cleanup(192): orig_line is 1, orig_col is 2, text() is 'define'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 1, orig_col is 2, type is PP_DEFINE, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x1:IN_PREPROC]
parse_cleanup(350): orig_line is 1, type is PP_DEFINE, text() is 'define'
parse_cleanup(352): frm.stmt_count is 1, frm.expr_count is 1
parse_cleanup(371): frm.stmt_count is 2, frm.expr_count is 2
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 1, orig_col is 2, text() is 'define'
print_stack(161): str is 'define' [PP_DEFINE]
brace_cleanup(192): orig_line is 1, orig_col is 9, text() is 'FOO'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 1, orig_col is 9, type is MACRO, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x1:IN_PREPROC]
parse_cleanup(350): orig_line is 1, type is MACRO, text() is 'FOO'
parse_cleanup(352): frm.stmt_count is 2, frm.expr_count is 2
parse_cleanup(371): frm.stmt_count is 3, frm.expr_count is 3
parse_cleanup(723):
parse_cleanup(832): orig_line is 1, reset1 stmt on 'FOO'
parse_cleanup(836): frm.stmt_count is 0, frm.expr_count is 0
parse_cleanup(840): Mark expression starts: orig_line is 1, orig_col is 9, text() is 'FOO'
print_stack(161): str is 'FOO' [PP_DEFINE]
brace_cleanup(192): orig_line is 1, orig_col is 12, text() is ''
fl_copy_tos(103): frame_count is 1
fl_trash_tos(123): frame_count is 0
brace_cleanup(210): pp_level is 0
brace_cleanup(192): orig_line is 2, orig_col is 1, text() is '#'
fl_push(136): frame_count is 1
ParseFrame::push(push:152): orig_line is 0, orig_col is 0, type is NONE, brace_level is 0, level is 0, pse_tos: 0 -> 1
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 2, orig_col is 1, type is PREPROC, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x200000001:IN_PREPROC,PUNCTUATOR]
parse_cleanup(350): orig_line is 2, type is PREPROC, text() is '#'
parse_cleanup(352): frm.stmt_count is 0, frm.expr_count is 0
chunk_flags_set_real(832): 0000000200000001^00000000000c0000=00000002000c0001
   orig_line is 2, orig_col is 1, text() '#', type is PREPROC, parent_type is PP_DEFINE,
   [CallStack: chunk_flags_set_real:824, parse_cleanup:340, brace_cleanup:183]
parse_cleanup(364): orig_line is 2, 1.marked '#' as stmt, start stmt_count is 0, expr_count is 0
parse_cleanup(371): frm.stmt_count is 1, frm.expr_count is 1
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 2, orig_col is 1, text() is '#'
print_stack(161): str is '#' [PP_DEFINE]
brace_cleanup(192): orig_line is 2, orig_col is 2, text() is 'define'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 2, orig_col is 2, type is PP_DEFINE, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x1:IN_PREPROC]
parse_cleanup(350): orig_line is 2, type is PP_DEFINE, text() is 'define'
parse_cleanup(352): frm.stmt_count is 1, frm.expr_count is 1
parse_cleanup(371): frm.stmt_count is 2, frm.expr_count is 2
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 2, orig_col is 2, text() is 'define'
print_stack(161): str is 'define' [PP_DEFINE]
brace_cleanup(192): orig_line is 2, orig_col is 9, text() is 'BAR'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 2, orig_col is 9, type is MACRO_FUNC, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x1:IN_PREPROC]
parse_cleanup(350): orig_line is 2, type is MACRO_FUNC, text() is 'BAR'
parse_cleanup(352): frm.stmt_count is 2, frm.expr_count is 2
parse_cleanup(371): frm.stmt_count is 3, frm.expr_count is 3
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 2, orig_col is 9, text() is 'BAR'
print_stack(161): str is 'BAR' [PP_DEFINE]
brace_cleanup(192): orig_line is 2, orig_col is 12, text() is '('
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 2, orig_col is 12, type is PAREN_OPEN, tos is 1, TOS.type is PP_DEFINE, TOS.stage is NONE, [0x200000001:IN_PREPROC,PUNCTUATOR]
parse_cleanup(350): orig_line is 2, type is PAREN_OPEN, text() is '('
parse_cleanup(352): frm.stmt_count is 3, frm.expr_count is 3
parse_cleanup(371): frm.stmt_count is 4, frm.expr_count is 4
ParseFrame::push(parse_cleanup:717): orig_line is 2, orig_col is 12, type is PAREN_OPEN, brace_level is 1, level is 1, pse_tos: 1 -> 2
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 2, orig_col is 12, text() is '('
parse_cleanup(873): orig_line is 2, orig_col is 12, reset expr on '('
print_stack(161): str is '(' [PP_DEFINE] [PAREN_OPEN]
brace_cleanup(192): orig_line is 2, orig_col is 13, text() is ')'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 2, orig_col is 13, type is PAREN_CLOSE, tos is 2, TOS.type is PAREN_OPEN, TOS.stage is NONE, [0x200000001:IN_PREPROC,PUNCTUATOR]
parse_cleanup(350): orig_line is 2, type is PAREN_CLOSE, text() is ')'
parse_cleanup(352): frm.stmt_count is 4, frm.expr_count is 0
parse_cleanup(371): frm.stmt_count is 5, frm.expr_count is 1
parse_cleanup(506): pc->orig_line is 2, orig_col is 13, text() is ')', type is PAREN_CLOSE
ParseFrame::pop (parse_cleanup:507): open_line is 2, clos_col is 12, type is PAREN_OPEN, cpd.level   is 0, level is 1, pse_tos: 2 -> 1
print_stack(161): str is '-Close  ' [PP_DEFINE]
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 2, orig_col is 13, text() is ')'
print_stack(161): str is ')' [PP_DEFINE]
brace_cleanup(192): orig_line is 2, orig_col is 14, text() is ''
fl_copy_tos(103): frame_count is 1
fl_trash_tos(123): frame_count is 0
brace_cleanup(210): pp_level is 0
brace_cleanup(192): orig_line is 4, orig_col is 1, text() is 'FOO'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 4, orig_col is 1, type is TYPE, tos is 0, TOS.type is EOF, TOS.stage is NONE, [0x0:]
parse_cleanup(350): orig_line is 4, type is TYPE, text() is 'FOO'
parse_cleanup(352): frm.stmt_count is 0, frm.expr_count is 0
chunk_flags_set_real(832): 0000000000000000^00000000000c0000=00000000000c0000
   orig_line is 4, orig_col is 1, text() 'FOO', type is TYPE, parent_type is NONE,
   [CallStack: chunk_flags_set_real:824, parse_cleanup:340, brace_cleanup:183]
parse_cleanup(364): orig_line is 4, 1.marked 'FOO' as stmt, start stmt_count is 0, expr_count is 0
parse_cleanup(371): frm.stmt_count is 1, frm.expr_count is 1
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 4, orig_col is 1, text() is 'FOO'
print_stack(161): str is 'FOO'
brace_cleanup(192): orig_line is 4, orig_col is 4, text() is ''
brace_cleanup(210): pp_level is 0
brace_cleanup(192): orig_line is 5, orig_col is 1, text() is 'BAR'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 5, orig_col is 1, type is WORD, tos is 0, TOS.type is EOF, TOS.stage is NONE, [0x0:]
parse_cleanup(350): orig_line is 5, type is WORD, text() is 'BAR'
parse_cleanup(352): frm.stmt_count is 1, frm.expr_count is 1
parse_cleanup(371): frm.stmt_count is 2, frm.expr_count is 2
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 5, orig_col is 1, text() is 'BAR'
print_stack(161): str is 'BAR'
brace_cleanup(192): orig_line is 5, orig_col is 4, text() is '('
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 5, orig_col is 4, type is PAREN_OPEN, tos is 0, TOS.type is EOF, TOS.stage is NONE, [0x200000000:PUNCTUATOR]
parse_cleanup(350): orig_line is 5, type is PAREN_OPEN, text() is '('
parse_cleanup(352): frm.stmt_count is 2, frm.expr_count is 2
parse_cleanup(371): frm.stmt_count is 3, frm.expr_count is 3
ParseFrame::push(parse_cleanup:717): orig_line is 5, orig_col is 4, type is PAREN_OPEN, brace_level is 0, level is 0, pse_tos: 0 -> 1
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 5, orig_col is 4, text() is '('
parse_cleanup(873): orig_line is 5, orig_col is 4, reset expr on '('
print_stack(161): str is '(' [PAREN_OPEN]
brace_cleanup(192): orig_line is 5, orig_col is 5, text() is ')'
brace_cleanup(210): pp_level is 0
parse_cleanup(343): orig_line is 5, orig_col is 5, type is PAREN_CLOSE, tos is 1, TOS.type is PAREN_OPEN, TOS.stage is NONE, [0x200000000:PUNCTUATOR]
parse_cleanup(350): orig_line is 5, type is PAREN_CLOSE, text() is ')'
parse_cleanup(352): frm.stmt_count is 3, frm.expr_count is 0
parse_cleanup(371): frm.stmt_count is 4, frm.expr_count is 1
parse_cleanup(506): pc->orig_line is 5, orig_col is 5, text() is ')', type is PAREN_CLOSE
ParseFrame::pop (parse_cleanup:507): open_line is 5, clos_col is 4, type is PAREN_OPEN, cpd.level   is 0, level is 0, pse_tos: 1 -> 0
print_stack(161): str is '-Close  '
parse_cleanup(723):
parse_cleanup(840): Mark expression starts: orig_line is 5, orig_col is 5, text() is ')'
print_stack(161): str is ')'
brace_cleanup(192): orig_line is 5, orig_col is 6, text() is ''
brace_cleanup(210): pp_level is 0
chunk_flags_set_real(832): 0000000000000001^0000000000080000=0000000000080001
   orig_line is 2, orig_col is 9, text() 'BAR', type is MACRO_FUNC, parent_type is NONE,
   [CallStack: chunk_flags_set_real:824, mark_define_expressions:907, fix_symbols:1796]
chunk_flags_set_real(832): 0000000200000001^0000000000080000=0000000200080001
   orig_line is 2, orig_col is 13, text() ')', type is PAREN_CLOSE, parent_type is NONE,
   [CallStack: chunk_flags_set_real:824, mark_define_expressions:907, fix_symbols:1796]
fix_symbols(1871): pc->orig_line       is 1, orig_col is 1, text() is '#', type is PREPROC
fix_symbols(1894): next->orig_line     is 1, orig_col is 2, text() is 'define', type is PP_DEFINE
fix_symbols(1897): do_symbol_check(, #, define)
fix_symbols(1871): pc->orig_line       is 1, orig_col is 2, text() is 'define', type is PP_DEFINE
fix_symbols(1882): prev(ni)->orig_line is 1, orig_col is 1, text() is '#', type is PREPROC
fix_symbols(1894): next->orig_line     is 1, orig_col is 9, text() is 'FOO', type is MACRO
fix_symbols(1897): do_symbol_check(#, define, FOO)
fix_symbols(1871): pc->orig_line       is 1, orig_col is 9, text() is 'FOO', type is MACRO
fix_symbols(1882): prev(ni)->orig_line is 1, orig_col is 2, text() is 'define', type is PP_DEFINE
fix_symbols(1897): do_symbol_check(define, FOO, )
fix_symbols(1871): pc->orig_line       is 2, orig_col is 1, text() is '#', type is PREPROC
fix_symbols(1894): next->orig_line     is 2, orig_col is 2, text() is 'define', type is PP_DEFINE
fix_symbols(1897): do_symbol_check(, #, define)
fix_symbols(1871): pc->orig_line       is 2, orig_col is 2, text() is 'define', type is PP_DEFINE
fix_symbols(1882): prev(ni)->orig_line is 2, orig_col is 1, text() is '#', type is PREPROC
fix_symbols(1894): next->orig_line     is 2, orig_col is 9, text() is 'BAR', type is MACRO_FUNC
fix_symbols(1897): do_symbol_check(#, define, BAR)
fix_symbols(1871): pc->orig_line       is 2, orig_col is 9, text() is 'BAR', type is MACRO_FUNC
fix_symbols(1882): prev(ni)->orig_line is 2, orig_col is 2, text() is 'define', type is PP_DEFINE
fix_symbols(1894): next->orig_line     is 2, orig_col is 12, text() is '(', type is PAREN_OPEN
fix_symbols(1897): do_symbol_check(define, BAR, ()
flag_parens(29): between  po is '(', orig_line is 2, orig_col is 12, and
flag_parens(31): paren_close is ')', orig_line is 2, orig_col is 13, type is FPAREN_OPEN, parent_type is MACRO_FUNC
 [CallStack: flag_parens:15, do_symbol_check:326, fix_symbols:1796]
chunk_flags_set_real(832): 0000000200080001^0000000000000010=0000000200080011
   orig_line is 2, orig_col is 13, text() ')', type is PAREN_CLOSE, parent_type is NONE,
   [CallStack: chunk_flags_set_real:824, flag_parens:15, do_symbol_check:326, fix_symbols:1796]
flag_parens(61): orig_line is 2, orig_col is 12, pc->text() '('
   pc->type is PAREN_OPEN, pc->parent_type is NONE => *type is FPAREN_OPEN, *parent_type is NONE
flag_parens(62): orig_line is 2, orig_col is 13, pc->text() ')'
   pc->type is PAREN_CLOSE, pc->parent_type is NONE => *type is FPAREN_CLOSE, *parent_type is NONE
flag_parens(67): orig_line is 2, orig_col is 12, pc->text() '('
   pc->type is FPAREN_OPEN, pc->parent_type is NONE => *type is MACRO_FUNC, *parent_type is NONE
flag_parens(68): orig_line is 2, orig_col is 13, pc->text() ')'
   pc->type is FPAREN_CLOSE, pc->parent_type is NONE => *type is MACRO_FUNC, *parent_type is NONE
fix_symbols(1871): pc->orig_line       is 2, orig_col is 12, text() is '(', type is FPAREN_OPEN
fix_symbols(1882): prev(ni)->orig_line is 2, orig_col is 9, text() is 'BAR', type is MACRO_FUNC
fix_symbols(1894): next->orig_line     is 2, orig_col is 13, text() is ')', type is FPAREN_CLOSE
fix_symbols(1897): do_symbol_check(BAR, (, ))
fix_symbols(1871): pc->orig_line       is 2, orig_col is 13, text() is ')', type is FPAREN_CLOSE
fix_symbols(1882): prev(ni)->orig_line is 2, orig_col is 12, text() is '(', type is FPAREN_OPEN
fix_symbols(1897): do_symbol_check((, ), )
fix_symbols(1871): pc->orig_line       is 4, orig_col is 1, text() is 'FOO', type is TYPE
fix_symbols(1894): next->orig_line     is 5, orig_col is 1, text() is 'BAR', type is WORD
fix_symbols(1897): do_symbol_check(, FOO, BAR)
fix_symbols(1871): pc->orig_line       is 5, orig_col is 1, text() is 'BAR', type is WORD
fix_symbols(1882): prev(ni)->orig_line is 4, orig_col is 1, text() is 'FOO', type is TYPE
fix_symbols(1894): next->orig_line     is 5, orig_col is 4, text() is '(', type is PAREN_OPEN
fix_symbols(1897): do_symbol_check(FOO, BAR, ()
do_symbol_check(829): orig_line is 5, orig_col is 1, pc->text() 'BAR'
   pc->type is WORD, pc->parent_type is NONE => *type is FUNCTION, *parent_type is NONE
mark_function(1146): orig_line is 5, orig_col is 1, text() 'BAR'
mark_function(1258): orig_line is 5, orig_col is 1, text() 'BAR, type is FUNCTION, parent_type is NONE
   level is 0, brace_level is 0, next->text() '(', next->type is PAREN_OPEN, next->level is 0
mark_function(1397): examine: text() is 'BAR', orig_line is 5, orig_col is 1, type is FUNCTION
mark_function(1412): (11) SET TO CT_FUNC_CALL: orig_line is 5, orig_col is 1, text() 'BAR'
mark_function(1414): orig_line is 5, orig_col is 1, pc->text() 'BAR'
   pc->type is FUNCTION, pc->parent_type is NONE => *type is FUNC_CALL, *parent_type is NONE
mark_function(1418): Check for C++ function def, text() is 'BAR', orig_line is 5, orig_col is 1, type is FUNC_CALL
mark_function(1423): prev->text() is 'FOO', orig_line is 4, orig_col is 1, type is TYPE
mark_function(1499): pc->text() is 'BAR', orig_line is 5, orig_col is 1, type is FUNC_CALL
mark_function(1510): Checking func call: prev->text() 'FOO', prev->type is TYPE
mark_function(1538): next step with: prev->orig_line is 4, orig_col is 1, text() 'FOO'
mark_function(1641):   --> For sure a prototype or definition
mark_function(1775): pc is 'BAR', orig_line is 5, orig_col is 1, type is FUNC_CALL
mark_function(1777): (12) SET TO CT_FUNC_DEF: orig_line is 5, orig_col is 1, text() 'BAR'
mark_function(1778): orig_line is 5, orig_col is 1, pc->text() 'BAR'
   pc->type is FUNC_CALL, pc->parent_type is NONE => *type is FUNC_DEF, *parent_type is NONE
mark_function(1789): text() is 'FOO', type is TYPE
flag_parens(29): between  po is '(', orig_line is 5, orig_col is 4, and
flag_parens(31): paren_close is ')', orig_line is 5, orig_col is 5, type is FPAREN_OPEN, parent_type is FUNC_DEF
 [CallStack: flag_parens:15, mark_function:1139, do_symbol_check:326, fix_symbols:1796]
chunk_flags_set_real(832): 0000000200000000^0000000000000008=0000000200000008
   orig_line is 5, orig_col is 5, text() ')', type is PAREN_CLOSE, parent_type is NONE,
   [CallStack: chunk_flags_set_real:824, flag_parens:15, mark_function:1139, do_symbol_check:326, fix_symbols:1796]
flag_parens(61): orig_line is 5, orig_col is 4, pc->text() '('
   pc->type is PAREN_OPEN, pc->parent_type is NONE => *type is FPAREN_OPEN, *parent_type is NONE
flag_parens(62): orig_line is 5, orig_col is 5, pc->text() ')'
   pc->type is PAREN_CLOSE, pc->parent_type is NONE => *type is FPAREN_CLOSE, *parent_type is NONE
flag_parens(67): orig_line is 5, orig_col is 4, pc->text() '('
   pc->type is FPAREN_OPEN, pc->parent_type is NONE => *type is FUNC_DEF, *parent_type is NONE
flag_parens(68): orig_line is 5, orig_col is 5, pc->text() ')'
   pc->type is FPAREN_CLOSE, pc->parent_type is NONE => *type is FUNC_DEF, *parent_type is NONE
fix_fcn_def_params(312): text() '(', type is FPAREN_OPEN, on orig_line 5, level is 0
fix_fcn_def_params(339): bailed on text() ')', on orig_line 5
mark_function_return_type(1011): (backwards) return type for 'BAR' @ orig_line is 5, orig_col is 1
mark_function_return_type(1018): orig_line is 4, orig_col is 1, text() 'FOO', type is TYPE, [0xc0000:STMT_START,EXPR_START]
mark_function_return_type(1018): orig_line is 2, orig_col is 13, text() ')', type is FPAREN_CLOSE, [0x200080011:IN_PREPROC,IN_FCN_CALL,EXPR_START,PUNCTUATOR]
mark_function_return_type(1053): marking returns... text() 'FOO', type is TYPE
mark_function_return_type(1072): orig_line is 4, orig_col is 1, pc->text() 'FOO'
   pc->type is TYPE, pc->parent_type is NONE => *type is FUNC_DEF, *parent_type is NONE

flag_parens(29): between  po is '(', orig_line is 5, orig_col is 4, and
flag_parens(31): paren_close is ')', orig_line is 5, orig_col is 5, type is FPAREN_OPEN, parent_type is FUNC_DEF
 [CallStack: flag_parens:15, do_symbol_check:326, fix_symbols:1796]
fix_symbols(1871): pc->orig_line       is 5, orig_col is 4, text() is '(', type is FPAREN_OPEN
fix_symbols(1882): prev(ni)->orig_line is 5, orig_col is 1, text() is 'BAR', type is FUNC_DEF
fix_symbols(1894): next->orig_line     is 5, orig_col is 5, text() is ')', type is FPAREN_CLOSE
fix_symbols(1897): do_symbol_check(BAR, (, ))
fix_symbols(1871): pc->orig_line       is 5, orig_col is 5, text() is ')', type is FPAREN_CLOSE
fix_symbols(1882): prev(ni)->orig_line is 5, orig_col is 4, text() is '(', type is FPAREN_OPEN
fix_symbols(1897): do_symbol_check((, ), )
fix_symbols(1915): pc->orig_line is 1, orig_col is 1, text() is '#', type is PREPROC, parent_type is PP_DEFINE
fix_symbols(1986): pc->orig_line is 1, orig_col is 1, text() is '#', type is PREPROC, parent_type is PP_DEFINE
   [0x2000c0001:IN_PREPROC,STMT_START,EXPR_START,PUNCTUATOR]
fix_symbols(1915): pc->orig_line is 1, orig_col is 2, text() is 'define', type is PP_DEFINE, parent_type is NONE
fix_symbols(1986): pc->orig_line is 1, orig_col is 2, text() is 'define', type is PP_DEFINE, parent_type is NONE
   [0x1:IN_PREPROC]
fix_symbols(1915): pc->orig_line is 1, orig_col is 9, text() is 'FOO', type is MACRO, parent_type is NONE
fix_symbols(1986): pc->orig_line is 1, orig_col is 9, text() is 'FOO', type is MACRO, parent_type is NONE
   [0x1:IN_PREPROC]
fix_symbols(1915): pc->orig_line is 2, orig_col is 1, text() is '#', type is PREPROC, parent_type is PP_DEFINE
fix_symbols(1986): pc->orig_line is 2, orig_col is 1, text() is '#', type is PREPROC, parent_type is PP_DEFINE
   [0x2000c0001:IN_PREPROC,STMT_START,EXPR_START,PUNCTUATOR]
fix_symbols(1915): pc->orig_line is 2, orig_col is 2, text() is 'define', type is PP_DEFINE, parent_type is NONE
fix_symbols(1986): pc->orig_line is 2, orig_col is 2, text() is 'define', type is PP_DEFINE, parent_type is NONE
   [0x1:IN_PREPROC]
fix_symbols(1915): pc->orig_line is 2, orig_col is 9, text() is 'BAR', type is MACRO_FUNC, parent_type is NONE
fix_symbols(1986): pc->orig_line is 2, orig_col is 9, text() is 'BAR', type is MACRO_FUNC, parent_type is NONE
   [0x80001:IN_PREPROC,EXPR_START]
fix_symbols(1915): pc->orig_line is 2, orig_col is 12, text() is '(', type is FPAREN_OPEN, parent_type is MACRO_FUNC
fix_symbols(1986): pc->orig_line is 2, orig_col is 12, text() is '(', type is FPAREN_OPEN, parent_type is MACRO_FUNC
   [0x200000001:IN_PREPROC,PUNCTUATOR]
fix_symbols(1915): pc->orig_line is 2, orig_col is 13, text() is ')', type is FPAREN_CLOSE, parent_type is MACRO_FUNC
fix_symbols(1986): pc->orig_line is 2, orig_col is 13, text() is ')', type is FPAREN_CLOSE, parent_type is MACRO_FUNC
   [0x200080011:IN_PREPROC,IN_FCN_CALL,EXPR_START,PUNCTUATOR]
fix_symbols(1915): pc->orig_line is 4, orig_col is 1, text() is 'FOO', type is TYPE, parent_type is FUNC_DEF
fix_symbols(1986): pc->orig_line is 4, orig_col is 1, text() is 'FOO', type is TYPE, parent_type is FUNC_DEF
   [0xc0000:STMT_START,EXPR_START]
fix_variable_definition(626): start at pc->orig_line is 4, pc->orig_col is 1
fix_variable_definition(638):   1:pc->text() 'FOO', type is TYPE
fix_variable_definition(648):   2:pc->text() 'BAR', type is FUNC_DEF
fix_variable_definition(659):   3:pc->text() 'BAR', type is FUNC_DEF
fix_variable_definition(669):   4:pc->text() 'BAR', type is FUNC_DEF
fix_variable_definition(684): end->type is FUNC_DEF
tokenize_trailing_return_types(167): orig_line is 1, orig_col is 1, text() is '#'
tokenize_trailing_return_types(167): orig_line is 1, orig_col is 2, text() is 'define'
tokenize_trailing_return_types(167): orig_line is 1, orig_col is 9, text() is 'FOO'
tokenize_trailing_return_types(167): orig_line is 2, orig_col is 1, text() is '#'
tokenize_trailing_return_types(167): orig_line is 2, orig_col is 2, text() is 'define'
tokenize_trailing_return_types(167): orig_line is 2, orig_col is 9, text() is 'BAR'
tokenize_trailing_return_types(167): orig_line is 2, orig_col is 12, text() is '('
tokenize_trailing_return_types(167): orig_line is 2, orig_col is 13, text() is ')'
tokenize_trailing_return_types(167): orig_line is 4, orig_col is 1, text() is 'FOO'
tokenize_trailing_return_types(167): orig_line is 5, orig_col is 1, text() is 'BAR'
tokenize_trailing_return_types(167): orig_line is 5, orig_col is 4, text() is '('
tokenize_trailing_return_types(167): orig_line is 5, orig_col is 5, text() is ')'
combine_labels(97): next->orig_line is 1, next->orig_col is 9, text() 'FOO'
combine_labels(82): next->orig_line is 1, next->orig_col is 12, <Newline>, nl is 1
combine_labels(97): next->orig_line is 2, next->orig_col is 1, text() '#'
combine_labels(97): next->orig_line is 2, next->orig_col is 2, text() 'define'
combine_labels(97): next->orig_line is 2, next->orig_col is 9, text() 'BAR'
combine_labels(97): next->orig_line is 2, next->orig_col is 12, text() '('
combine_labels(97): next->orig_line is 2, next->orig_col is 13, text() ')'
combine_labels(82): next->orig_line is 2, next->orig_col is 14, <Newline>, nl is 2
combine_labels(97): next->orig_line is 4, next->orig_col is 1, text() 'FOO'
combine_labels(82): next->orig_line is 4, next->orig_col is 4, <Newline>, nl is 1
combine_labels(97): next->orig_line is 5, next->orig_col is 1, text() 'BAR'
combine_labels(97): next->orig_line is 5, next->orig_col is 4, text() '('
combine_labels(97): next->orig_line is 5, next->orig_col is 5, text() ')'
combine_labels(82): next->orig_line is 5, next->orig_col is 6, <Newline>, nl is 1
log_rule(enum_cleanup:22): rule is 'mod_enum_last_comma'
log_rule(do_braces:197): rule is 'mod_full_brace_if_chain'
log_rule(do_braces:198): rule is 'mod_full_brace_if_chain_only'
log_rule(do_braces:205): rule is 'mod_full_brace_if'
log_rule(do_braces:206): rule is 'mod_full_brace_do'
log_rule(do_braces:207): rule is 'mod_full_brace_for'
log_rule(do_braces:208): rule is 'mod_full_brace_using'
log_rule(do_braces:209): rule is 'mod_full_brace_while'
log_rule(do_braces:220): rule is 'mod_full_brace_if'
log_rule(do_braces:221): rule is 'mod_full_brace_do'
log_rule(do_braces:222): rule is 'mod_full_brace_for'
log_rule(do_braces:223): rule is 'mod_full_brace_function'
log_rule(do_braces:224): rule is 'mod_full_brace_using'
log_rule(do_braces:225): rule is 'mod_full_brace_while'
log_rule(do_braces:236): rule is 'mod_case_brace'
log_rule(do_braces:242): rule is 'mod_move_case_break'
log_rule(uncrustify_file:2068): rule is 'mod_remove_extra_semicolon'
log_rule(uncrustify_file:2075): rule is 'mod_remove_empty_return'
log_rule(do_parens:47): rule is 'mod_full_paren_if_bool'
log_rule(uncrustify_file:2088): rule is 'nl_remove_extra_newlines'
Newline loop start: 0
newlines_cleanup_braces(3771): orig_line is 1, orig_col is 1, text() is '#'
newlines_cleanup_braces(3771): orig_line is 1, orig_col is 2, text() is 'define'
newlines_cleanup_braces(3771): orig_line is 1, orig_col is 9, text() is 'FOO'
newlines_cleanup_braces(3771): orig_line is 2, orig_col is 1, text() is '#'
newlines_cleanup_braces(3771): orig_line is 2, orig_col is 2, text() is 'define'
newlines_cleanup_braces(3771): orig_line is 2, orig_col is 9, text() is 'BAR'
newlines_cleanup_braces(3771): orig_line is 2, orig_col is 12, text() is '('
log_rule(newlines_cleanup_braces:4576): rule is 'nl_func_decl_start'
log_rule(newlines_cleanup_braces:4577): rule is 'nl_func_def_start'
log_rule(newlines_cleanup_braces:4578): rule is 'nl_func_decl_start_single'
log_rule(newlines_cleanup_braces:4579): rule is 'nl_func_def_start_single'
log_rule(newlines_cleanup_braces:4580): rule is 'nl_func_decl_start_multi_line'
log_rule(newlines_cleanup_braces:4581): rule is 'nl_func_def_start_multi_line'
log_rule(newlines_cleanup_braces:4582): rule is 'nl_func_decl_args'
log_rule(newlines_cleanup_braces:4583): rule is 'nl_func_def_args'
log_rule(newlines_cleanup_braces:4584): rule is 'nl_func_decl_args_multi_line'
log_rule(newlines_cleanup_braces:4585): rule is 'nl_func_def_args_multi_line'
log_rule(newlines_cleanup_braces:4586): rule is 'nl_func_decl_end'
log_rule(newlines_cleanup_braces:4587): rule is 'nl_func_def_end'
log_rule(newlines_cleanup_braces:4588): rule is 'nl_func_decl_end_single'
log_rule(newlines_cleanup_braces:4589): rule is 'nl_func_def_end_single'
log_rule(newlines_cleanup_braces:4590): rule is 'nl_func_decl_end_multi_line'
log_rule(newlines_cleanup_braces:4591): rule is 'nl_func_def_end_multi_line'
log_rule(newlines_cleanup_braces:4592): rule is 'nl_func_decl_empty'
log_rule(newlines_cleanup_braces:4593): rule is 'nl_func_def_empty'
log_rule(newlines_cleanup_braces:4594): rule is 'nl_func_type_name'
log_rule(newlines_cleanup_braces:4595): rule is 'nl_func_type_name_class'
log_rule(newlines_cleanup_braces:4596): rule is 'nl_func_class_scope'
log_rule(newlines_cleanup_braces:4597): rule is 'nl_func_scope_name'
log_rule(newlines_cleanup_braces:4598): rule is 'nl_func_proto_type_name'
log_rule(newlines_cleanup_braces:4599): rule is 'nl_func_paren'
log_rule(newlines_cleanup_braces:4600): rule is 'nl_func_def_paren'
log_rule(newlines_cleanup_braces:4601): rule is 'nl_func_def_paren_empty'
log_rule(newlines_cleanup_braces:4602): rule is 'nl_func_paren_empty'
log_rule(newlines_cleanup_braces:4603): rule is 'nl_func_call_args'
newlines_cleanup_braces(3771): orig_line is 2, orig_col is 13, text() is ')'
newlines_cleanup_braces(3771): orig_line is 4, orig_col is 1, text() is 'FOO'
newlines_cleanup_braces(3771): orig_line is 5, orig_col is 1, text() is 'BAR'
newlines_cleanup_braces(3771): orig_line is 5, orig_col is 4, text() is '('
log_rule(newlines_cleanup_braces:4576): rule is 'nl_func_decl_start'
log_rule(newlines_cleanup_braces:4577): rule is 'nl_func_def_start'
log_rule(newlines_cleanup_braces:4578): rule is 'nl_func_decl_start_single'
log_rule(newlines_cleanup_braces:4579): rule is 'nl_func_def_start_single'
log_rule(newlines_cleanup_braces:4580): rule is 'nl_func_decl_start_multi_line'
log_rule(newlines_cleanup_braces:4581): rule is 'nl_func_def_start_multi_line'
log_rule(newlines_cleanup_braces:4582): rule is 'nl_func_decl_args'
log_rule(newlines_cleanup_braces:4583): rule is 'nl_func_def_args'
log_rule(newlines_cleanup_braces:4584): rule is 'nl_func_decl_args_multi_line'
log_rule(newlines_cleanup_braces:4585): rule is 'nl_func_def_args_multi_line'
log_rule(newlines_cleanup_braces:4586): rule is 'nl_func_decl_end'
log_rule(newlines_cleanup_braces:4587): rule is 'nl_func_def_end'
log_rule(newlines_cleanup_braces:4588): rule is 'nl_func_decl_end_single'
log_rule(newlines_cleanup_braces:4589): rule is 'nl_func_def_end_single'
log_rule(newlines_cleanup_braces:4590): rule is 'nl_func_decl_end_multi_line'
log_rule(newlines_cleanup_braces:4591): rule is 'nl_func_def_end_multi_line'
log_rule(newlines_cleanup_braces:4592): rule is 'nl_func_decl_empty'
log_rule(newlines_cleanup_braces:4593): rule is 'nl_func_def_empty'
log_rule(newlines_cleanup_braces:4594): rule is 'nl_func_type_name'
log_rule(newlines_cleanup_braces:4595): rule is 'nl_func_type_name_class'
log_rule(newlines_cleanup_braces:4596): rule is 'nl_func_class_scope'
log_rule(newlines_cleanup_braces:4597): rule is 'nl_func_scope_name'
log_rule(newlines_cleanup_braces:4598): rule is 'nl_func_proto_type_name'
log_rule(newlines_cleanup_braces:4599): rule is 'nl_func_paren'
log_rule(newlines_cleanup_braces:4600): rule is 'nl_func_def_paren'
log_rule(newlines_cleanup_braces:4601): rule is 'nl_func_def_paren_empty'
log_rule(newlines_cleanup_braces:4602): rule is 'nl_func_paren_empty'
log_rule(newlines_cleanup_braces:4603): rule is 'nl_func_call_args'
newline_func_def_or_call(3059): called on start->text() is '(', orig_line is 5, orig_col is 4, [FPAREN_OPEN/FUNC_DEF]
newline_func_def_or_call(3068): is_def is TRUE, is_call is FALSE
log_rule(newline_func_def_or_call:3112): rule is 'nl_func_def_paren'
log_rule(newline_func_def_or_call:3113): rule is 'nl_func_paren'
newline_func_def_or_call(3117): atmp is IGNORE
log_rule(newline_func_def_or_call:3137): rule is 'nl_func_class_scope'
log_rule(newline_func_def_or_call:3187): rule is 'nl_func_leave_one_liners'
```

Backtrace (using Uncrustify debug build):

```
$ gdb uncrustify
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.                                                                            
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from uncrustify...
(No debugging symbols found in uncrustify)
(gdb) run -c test.cfg test.c
Starting program: /usr/local/bin/uncrustify -c test.cfg test.c
Output suffix: .uncrustify
Parsing: test.c as language C

Program received signal SIGSEGV, Segmentation fault.
0x0000555555699abb in uncrustify::flags<pcf_flag_e>::operator&(pcf_flag_e) const ()
(gdb) bt
#0  0x0000555555699abb in uncrustify::flags<pcf_flag_e>::operator&(pcf_flag_e) const ()
#1  0x0000555555699b12 in uncrustify::flags<pcf_flag_e>::test(pcf_flag_e) const ()
#2  0x000055555571c4f7 in newline_func_def_or_call(chunk_t*) ()
#3  0x0000555555721f5a in newlines_cleanup_braces(bool) ()
#4  0x00005555557c7ae3 in uncrustify_file(file_mem const&, _IO_FILE*, char const*, bool) ()
#5  0x00005555557c68f3 in do_source_file(char const*, char const*, char const*, bool, bool) ()
#6  0x00005555557c4bfc in main ()
```

### PR DESCRIPTION
**Pull request by alexhenrie**
Fixes #3274

### CODE REVIEW

File: src/newlines.cpp [hunk 1]
```diff
@@ -3197,7 +3197,7 @@ static void newline_func_def_or_call(chunk_t *start)
                log_rule_B("nl_func_leave_one_liners");
 
                if (  options::nl_func_leave_one_liners()
-                  && brace->flags.test(PCF_ONE_LINER))                 // Issue #1511
+                  && (!brace || brace->flags.test(PCF_ONE_LINER)))     // Issue #1511 and #3274
```
Comment (gmaurel) [inline src/newlines.cpp:3200]: please use:
`brace != nullptr`

**Review by gmaurel — CHANGES_REQUESTED** [review]
a little change...

**Comment by gmaurel** [comment]
I like to have:
```.cpp
if (  options::nl_func_leave_one_liners()
   && (  brace == nullptr
         || brace->flags.test(PCF_ONE_LINER)))   // Issue #1511 and #3274
```

**Comment by alexhenrie** [comment]
Done

**Review by gmaurel — APPROVED** [review]
fine, thanks

**Comment by alexhenrie** [comment]
Thank you!
